Repository pokt-network/poktroll, pull requests merged in 2023-12, with the labels that each got.

#237 [Testing] chore: add testkeyring pkg
  Makefile
  pkg/relayer/miner/gen/gen_fixtures.go
  pkg/relayer/miner/gen/template.go
  pkg/relayer/miner/miner_test.go
  pkg/relayer/miner/relay_fixtures_test.go
  testutil/testkeyring/accounts.go
  testutil/testkeyring/accounts_table.go
  testutil/testkeyring/gen_accounts/gen.go
  testutil/testkeyring/gen_accounts/template.go
  testutil/testkeyring/keyring.go
Labels: enhancement, testing

#209 [Off-chain, Polylog] test: add testutils
  pkg/polylog/interface.go
  testutil/testpolylog/event.go
Labels: off-chain, code health

#211 [Off-chain, Polylog] chore: add zerolog logger implementation
  go.mod
  pkg/polylog/context.go
  pkg/polylog/godoc.go
  pkg/polylog/polyzero/event.go
  pkg/polylog/polyzero/godoc.go
  pkg/polylog/polyzero/levels.go
  pkg/polylog/polyzero/logger.go
  pkg/polylog/polyzero/logger_example_test.go
  pkg/polylog/polyzero/logger_test.go
  pkg/polylog/polyzero/options.go
Labels: off-chain, code health

#218 [Off-chain, Polylog] feat: polylog context integration
  Makefile
  pkg/polylog/context.go
  pkg/polylog/context_example_test.go
  pkg/polylog/context_test.go
  pkg/polylog/polyzero/default.go
  pkg/polylog/polyzero/test_logger.go
Labels: off-chain, tooling

#219 [Off-chain, Polylog] refactor: replace std logger usage in pkg/... with polylog
  pkg/appgateserver/cmd/cmd.go
  pkg/appgateserver/endpoint_selector.go
  pkg/appgateserver/error_reply.go
  pkg/appgateserver/server.go
  pkg/appgateserver/synchronous.go
  pkg/crypto/rings/cache.go
  pkg/observable/channel/observer.go
  pkg/observable/channel/replay.go
  pkg/observable/logging/logging.go
  pkg/partials/interface.go
  pkg/partials/partial.go
  pkg/partials/partials_test.go
  pkg/partials/payloads/jsonrpc.go
  pkg/partials/payloads/rest.go
  pkg/relayer/cmd/cmd.go
  pkg/relayer/protocol/block_heights.go
  pkg/relayer/proxy/error_reply.go
  pkg/relayer/proxy/proxy.go
  pkg/relayer/proxy/relay_builders.go
  pkg/relayer/proxy/relay_verifier.go
  pkg/relayer/proxy/server_builder.go
  pkg/relayer/proxy/synchronous.go
  pkg/relayer/relayminer.go
  pkg/relayer/relayminer_test.go
  pkg/relayer/session/claim.go
  pkg/relayer/session/proof.go
  pkg/relayer/session/session.go
  pkg/relayer/session/session_test.go
  pkg/retry/retry.go
  testutil/testclient/testblock/client.go
  testutil/testpolylog/logger.go
Labels: off-chain, tooling

#245 Make Relay{Request,Response}.GetSignableBytes return the signable hash
  pkg/appgateserver/relay_verifier.go
  pkg/appgateserver/synchronous.go
  pkg/relayer/proxy/relay_signer.go
  pkg/relayer/proxy/relay_verifier.go
  x/service/types/relay.go
Labels: off-chain, code health, crypto

#247 [🪲Off-chain, Polylog] fix: broken localnet output 🙄
  pkg/appgateserver/cmd/cmd.go
  pkg/deps/config/suppliers.go
  pkg/polylog/polyzero/logger.go
  pkg/relayer/cmd/cmd.go
Labels: bug, off-chain, tooling

#249 [CI] Pin ignite version to 0.27.2
  .github/workflows/main-build.yml
  .github/workflows/run-tests.yml
Labels: infra

#199 [RelayerProxy] Test relayer proxy startup
  pkg/appgateserver/relay_verifier.go
  pkg/appgateserver/synchronous.go
  pkg/client/interface.go
  pkg/client/query/errors.go
  pkg/client/query/sessionquerier.go
  pkg/client/query/supplierquerier.go
  pkg/deps/config/suppliers.go
  pkg/relayer/cmd/cmd.go
  pkg/relayer/proxy/proxy.go
  pkg/relayer/proxy/proxy_test.go
  pkg/relayer/proxy/relay_builders.go
  pkg/relayer/proxy/relay_signer.go
  pkg/relayer/proxy/relay_verifier.go
  pkg/relayer/proxy/server_builder.go
  pkg/relayer/proxy/synchronous.go
  pkg/signer/interface.go
  pkg/signer/ring_signer.go
  pkg/signer/simple_signer.go
  testutil/testclient/testqueryclients/accquerier.go
  testutil/testclient/testqueryclients/appquerier.go
  testutil/testclient/testqueryclients/sessionquerier.go
  testutil/testclient/testqueryclients/supplierquerier.go
  testutil/testproxy/jsonrpc.go
  testutil/testproxy/relayerproxy.go
  x/service/types/relay.go
  x/session/keeper/session_hydrator.go
Labels: testing, proxy, off-chain, push-image, devnet, devnet-test-e2e

#236 [On-chain, Relayminer] chore: add claim msg validation
  app/app.go
  e2e/tests/init_test.go
  e2e/tests/session.feature
  e2e/tests/session_steps_test.go
  pkg/client/tx/client.go
  testutil/keeper/supplier.go
  testutil/network/network.go
  testutil/supplier/fixtures.go
  testutil/testclient/localnet.go
  x/session/keeper/session_hydrator.go
  x/supplier/client/cli/helpers_test.go
  x/supplier/client/cli/query_claim_test.go
  x/supplier/genesis_test.go
  x/supplier/keeper/claim_test.go
  x/supplier/keeper/keeper.go
  x/supplier/keeper/msg_server_create_claim.go
  x/supplier/keeper/msg_server_create_claim_test.go
  x/supplier/keeper/msg_server_stake_supplier_test.go
  x/supplier/keeper/msg_server_test.go
  x/supplier/keeper/msg_server_unstake_supplier_test.go
  x/supplier/keeper/params_test.go
  x/supplier/keeper/proof_test.go
  x/supplier/keeper/query_claim_test.go
  x/supplier/keeper/query_params_test.go
  x/supplier/keeper/query_proof_test.go
  x/supplier/keeper/query_supplier_test.go
  x/supplier/keeper/supplier_test.go
  x/supplier/types/expected_keepers.go
Labels: relayminer, on-chain, push-image, devnet, devnet-test-e2e

#251 Scaffolded Tokenomics module
  app/app.go
  docs/static/openapi.yml
  proto/poktroll/tokenomics/genesis.proto
  proto/poktroll/tokenomics/params.proto
  proto/poktroll/tokenomics/query.proto
  proto/poktroll/tokenomics/tx.proto
  testutil/keeper/tokenomics.go
  x/tokenomics/client/cli/query.go
  x/tokenomics/client/cli/query_params.go
  x/tokenomics/client/cli/tx.go
  x/tokenomics/genesis.go
  x/tokenomics/genesis_test.go
  x/tokenomics/keeper/keeper.go
  x/tokenomics/keeper/msg_server.go
  x/tokenomics/keeper/msg_server_test.go
  x/tokenomics/keeper/params.go
  x/tokenomics/keeper/params_test.go
  x/tokenomics/keeper/query.go
  x/tokenomics/keeper/query_params.go
  x/tokenomics/keeper/query_params_test.go
  x/tokenomics/module.go
  x/tokenomics/module_simulation.go
  x/tokenomics/simulation/helpers.go
  x/tokenomics/types/codec.go
  x/tokenomics/types/errors.go
  x/tokenomics/types/expected_keepers.go
  x/tokenomics/types/genesis.go
  x/tokenomics/types/genesis_test.go
  x/tokenomics/types/keys.go
  x/tokenomics/types/params.go
  x/tokenomics/types/types.go
Labels: protocol

#241 feat: Working SDK with AppGateServer integration
  pkg/appgateserver/cmd/cmd.go
  pkg/appgateserver/endpoint_selector.go
  pkg/appgateserver/errors.go
  pkg/appgateserver/server.go
  pkg/appgateserver/session.go
  pkg/appgateserver/synchronous.go
  pkg/client/interface.go
  pkg/client/query/accquerier.go
  pkg/client/query/appquerier.go
  pkg/client/query/sessionquerier.go
  pkg/client/services.go
  pkg/deps/config/suppliers.go
  pkg/sdk/deps_builder.go
  pkg/sdk/errors.go
  pkg/sdk/interface.go
  pkg/sdk/relay_verifier.go
  pkg/sdk/sdk.go
  pkg/sdk/send_relay.go
  pkg/sdk/session.go
Labels: gateway, off-chain, push-image, devnet, devnet-test-e2e

#254 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, testing

#258 [CI/E2E] e2e fixes for e2e fixes
  .github/workflows-helpers/run-e2e-test-job-template.yaml
  e2e/tests/node.go
  testutil/testclient/localnet.go
Labels: infra, push-image, devnet, devnet-test-e2e

#268 [Tooling] fix PR template testing checklist item formatting
  .github/pull_request_template.md
Labels: tooling

#261 [SDK] feat: Have distinct JSON-RPC and gRPC urls
  Tiltfile
  pkg/client/query/codec.go
  pkg/client/query/supplierquerier.go
  pkg/deps/config/suppliers.go
  pkg/sdk/deps_builder.go
  pkg/sdk/sdk.go
Labels: off-chain, push-image, devnet, devnet-test-e2e

#253 [Testing] Unit tests, E2E tests, logging and other Fixes / "Touchups"
  .github/workflows-helpers/run-e2e-test-job-template.yaml
  Dockerfile.dev
  Tiltfile
  app/app.go
  e2e/tests/node.go
  e2e/tests/relay.feature
  e2e/tests/session_steps_test.go
  go.mod
  localnet/kubernetes/values-relayminer.yaml
  pkg/client/block/block.go
  pkg/client/block/client.go
  pkg/client/delegation/client.go
  pkg/client/events/replay_client_example_test.go
  pkg/client/interface.go
  pkg/client/supplier/client.go
  pkg/client/supplier/client_test.go
  pkg/relayer/proxy/synchronous.go
  testutil/keeper/tokenomics.go
  testutil/network/network.go
  testutil/testclient/localnet.go
  testutil/testclient/testtx/client.go
  x/application/keeper/msg_server_delegate_to_gateway.go
  x/application/keeper/msg_server_delegate_to_gateway_test.go
  x/application/keeper/msg_server_stake_application.go
  x/application/keeper/msg_server_undelegate_from_gateway.go
  x/application/keeper/msg_server_undelegate_from_gateway_test.go
  x/application/keeper/msg_server_unstake_application.go
  x/gateway/keeper/msg_server_stake_gateway.go
  x/gateway/keeper/msg_server_unstake_gateway.go
  x/session/keeper/session_hydrator.go
  x/supplier/keeper/claim.go
  x/supplier/keeper/msg_server_stake_supplier.go
  x/supplier/keeper/msg_server_unstake_supplier.go
  x/tokenomics/genesis.go
  x/tokenomics/keeper/params.go
  x/tokenomics/keeper/query_params.go
  x/tokenomics/module.go
  x/tokenomics/module_simulation.go
Labels: testing, push-image, devnet, devnet-test-e2e

#269 [Tooling] fix: PR template typo 2
  .github/pull_request_template.md
Labels: code health, tooling

#262 [Testing, Code Health] refactor: `NewMinedRelay` to shared testutil
  pkg/relayer/session/session_test.go
  testutil/testrelayer/relays.go
Labels: testing, code health

#272 [Cleanup] Centralzie websocket url -> endpoint changes
  pkg/deps/config/suppliers.go
  pkg/deps/config/types.go
  pkg/relayer/config/relayminer_configs_reader.go
  pkg/relayer/proxy/relay_verifier.go
  pkg/sdk/deps_builder.go
  pkg/sdk/urls.go
Labels: code health

#252 [Docs] Introduce Docusaurus documentation
  .github/workflows/upload-pages-artifact.yml
  .gitignore
  Makefile
  README.md
  config.yml
  docusaurus/.gitignore
  docusaurus/README.md
  docusaurus/babel.config.js
  docusaurus/docs/README.md
  docusaurus/docs/architecture/_category_.json
  docusaurus/docs/architecture/network.md
  docusaurus/docs/contributing/_category_.json
  docusaurus/docs/contributing/contributing.md
  docusaurus/docs/img/quickstart_accounts.png
  docusaurus/docs/img/quickstart_applist.png
  docusaurus/docs/img/quickstart_localnet.png
  docusaurus/docs/infrastructure/_category_.json
  docusaurus/docs/infrastructure/localnet.md
  docusaurus/docs/packages/_category_.json
  docusaurus/docs/packages/pkg/client/_category_.json
  docusaurus/docs/packages/pkg/client/events.md
  docusaurus/docs/packages/pkg/client/pkg.md
  docusaurus/docs/packages/pkg/observable/_category_.json
  docusaurus/docs/packages/pkg/observable/observable.md
  docusaurus/docs/quickstart.md
  docusaurus/docs/roadmap/_category_.json
  docusaurus/docs/roadmap/roadmap.md
  docusaurus/docs/roadmap/roadmap_changelog.md
  docusaurus/docusaurus.config.js
  docusaurus/package-lock.json
  docusaurus/package.json
  docusaurus/sidebars.js
  docusaurus/static/.nojekyll
  docusaurus/static/img/logo.png
  e2e/tests/init_test.go
  pkg/client/events/replay_client_example_test.go
  pkg/relayer/proxy/relay_verifier.go
  summary.html
Labels: documentation

#267 [EventsReplayClient] Fix Replay Client Bugs
  docs/static/openapi.yml
  pkg/appgateserver/cmd/cmd.go
  pkg/client/block/client.go
  pkg/client/block/client_integration_test.go
  pkg/client/block/client_test.go
  pkg/client/delegation/client.go
  pkg/client/delegation/client_integration_test.go
  pkg/client/delegation/client_test.go
  pkg/client/delegation/godoc.go
  pkg/client/events/errors.go
  pkg/client/events/query_client.go
  pkg/client/events/replay_client.go
  pkg/client/events/replay_client_example_test.go
  pkg/client/events/replay_client_integration_test.go
  pkg/client/interface.go
  pkg/client/tx/client_integration_test.go
  pkg/deps/config/suppliers.go
  pkg/observable/channel/replay.go
  pkg/relayer/cmd/cmd.go
  pkg/retry/retry.go
  pkg/sdk/deps_builder.go
  testutil/testclient/testblock/client.go
  testutil/testclient/testdelegation/client.go
  testutil/testclient/testeventsquery/connection.go
  testutil/testclient/testtx/client.go
Labels: enhancement, off-chain, push-image, devnet, devnet-test-e2e
