Repository pokt-network/poktroll, pull requests merged in 2024-02, with the labels that each got.

#358 fix: bad error check for session claiming
  pkg/relayer/session/proof.go
  pkg/relayer/session/session.go
Labels: bug, session, push-image, devnet, devnet-test-e2e

#315 [Session] fix: Store block hashes for sessionId derivation usage
  testutil/keeper/session.go
  testutil/testclient/testqueryclients/sessionquerier.go
  testutil/testproxy/relayerproxy.go
  x/session/keeper/block_hash.go
  x/session/keeper/keeper.go
  x/session/keeper/query_get_session_test.go
  x/session/keeper/session_hydrator.go
  x/session/keeper/session_hydrator_test.go
  x/session/module.go
Labels: session, push-image, devnet, devnet-test-e2e

#328 [Supplier] feat: persistence proofs in submit proof msg handler (2)
  e2e/tests/session.feature
  e2e/tests/session_steps_test.go
  proto/pocket/supplier/query.proto
  x/session/keeper/query_get_session.go
  x/supplier/client/cli/tx_create_claim_test.go
  x/supplier/client/cli/tx_submit_proof_test.go
  x/supplier/keeper/msg_server_create_claim.go
  x/supplier/keeper/msg_server_create_claim_test.go
  x/supplier/keeper/msg_server_submit_proof.go
  x/supplier/types/errors.go
  x/supplier/types/message_create_claim.go
  x/supplier/types/message_create_claim_test.go
  x/supplier/types/message_submit_proof.go
  x/supplier/types/message_submit_proof_test.go
  x/supplier/types/query_validation.go
Labels: supplier, on-chain, push-image, devnet, devnet-test-e2e

#323 [Tokenomics] SettleSessionAccounting first implementation (emissions=burn)
  app/app.go
  e2e/tests/init_test.go
  e2e/tests/session.feature
  e2e/tests/tokenomics.feature
  go.mod
  pkg/sdk/errors.go
  testutil/keeper/tokenomics.go
  x/session/types/errors.go
  x/session/types/query_get_session_request.go
  x/session/types/session_header.go
  x/session/types/session_header_test.go
  x/supplier/keeper/msg_server_submit_proof.go
  x/tokenomics/genesis_test.go
  x/tokenomics/keeper/keeper.go
  x/tokenomics/keeper/msg_server_test.go
  x/tokenomics/keeper/msg_server_update_params.go
  x/tokenomics/keeper/msg_server_update_params_test.go
  x/tokenomics/keeper/query_params_test.go
  x/tokenomics/keeper/settle_session_accounting.go
  x/tokenomics/keeper/settle_session_accounting_test.go
  x/tokenomics/simulation/update_params.go
  x/tokenomics/types/errors.go
  x/tokenomics/types/expected_keepers.go
Labels: on-chain, push-image, devnet, devnet-test-e2e, tokenomics

#361 [Documentation] Add AppGateServer usage documentation
  docusaurus/docs/configs/appgate_server_config.md
  docusaurus/docs/packages/pkg/appgate_server/_category_.json
  docusaurus/docs/packages/pkg/appgate_server/main.md
Labels: documentation, application, gateway, off-chain

#339 [SDK] GetApplications SDK Method
  go.mod
  pkg/client/interface.go
  pkg/client/query/appquerier.go
  pkg/sdk/application.go
  pkg/sdk/errors.go
  pkg/sdk/interface.go
  pkg/sdk/sdk.go
Labels: enhancement, push-image, devnet, devnet-test-e2e

#369 [Cleanup] Replace all instances of `sender` address with `application` address
  docs/static/openapi.yml
  docusaurus/docs/configs/appgate_server_config.md
  pkg/appgateserver/cmd/cmd.go
  pkg/appgateserver/server.go
Labels: code health, push-image, devnet, devnet-test-e2e

#375 [CI] Fix CI
  Makefile
Labels: bug, infra

#367 [SDK Migration] Switch to celestia-da, bump rollkit, fix CI
  .github/workflows/main-build.yml
  .github/workflows/run-tests.yml
  .tool-versions
  Dockerfile.dev
  Makefile
  Tiltfile
  app/app.go
  go.mod
  localnet/kubernetes/celestia-rollkit.yaml
  localnet/poktrolld/config/app.toml
  localnet/poktrolld/config/client.toml
  localnet/poktrolld/config/config.toml
  tools/tools.go
Labels: bug, infra

#368 [Session] fix: session mismatch due to off-by-one block height
  e2e/tests/session.feature
  go.mod
  x/session/keeper/keeper.go
  x/session/keeper/query_get_session.go
  x/session/keeper/query_get_session_test.go
  x/session/keeper/session_hydrator.go
  x/session/keeper/session_hydrator_test.go
Labels: bug, session, push-image, devnet, devnet-test-e2e

#387 [Docs] Remove session-mismatch error workaround
  docusaurus/docs/quickstart.md
Labels: documentation

#364 [Docs] Baseline actor docs and move around some other files as well
  docusaurus/docs/actors/_category_.json
  docusaurus/docs/actors/actors.md
  docusaurus/docs/actors/appgate_server.md
  docusaurus/docs/actors/application.md
  docusaurus/docs/actors/gateway.md
  docusaurus/docs/actors/relay_miner.md
  docusaurus/docs/actors/supplier.md
  docusaurus/docs/infrastructure/_category_.json
  docusaurus/docs/packages/_category_.json
  docusaurus/docs/packages/appgate_server.md
  docusaurus/docs/packages/client_events.md
  docusaurus/docs/packages/client_package.md
  docusaurus/docs/packages/observable.md
  docusaurus/docs/packages/pkg/appgate_server/_category_.json
  docusaurus/docs/packages/pkg/client/_category_.json
  docusaurus/docs/packages/pkg/observable/_category_.json
  docusaurus/docs/packages/pkg/sdk/_category_.json
  docusaurus/docs/packages/sdk.md
  docusaurus/docs/protocol/_category_.json
  docusaurus/docs/protocol/claim_and_proof_lifecycle.md
  docusaurus/docs/protocol/probabilistic_proofs.md
  docusaurus/docs/protocol/relay_mining.md
  docusaurus/docs/protocol/ring_signatures.md
  docusaurus/docs/protocol/session.md
  docusaurus/docs/roadmap/_category_.json
Labels: documentation

#393 [Docs] First iteration of documentation for `Gateway`s and the `Claim & Proof Lifecycle`
  docusaurus/docs/packages/appgate_server.md
  docusaurus/docs/protocol/claim_and_proof_lifecycle.md
  docusaurus/docs/protocol/gateways.md
  docusaurus/docs/protocol/ring_signatures.md
  docusaurus/docusaurus.config.js
  docusaurus/package-lock.json
  docusaurus/package.json
  docusaurus/yarn.lock
Labels: documentation

#365 [Migration] Service module
  Makefile
  api/poktroll/service/genesis.pulsar.go
  api/poktroll/service/module/module.pulsar.go
  api/poktroll/service/params.pulsar.go
  api/poktroll/service/query.pulsar.go
  api/poktroll/service/service.pulsar.go
  api/poktroll/service/tx.pulsar.go
  api/poktroll/shared/service.pulsar.go
  app/app.go
  app/app_config.go
  cmd/poktrolld/cmd/root.go
  go.mod
  proto/poktroll/service/genesis.proto
  proto/poktroll/service/module/module.proto
  proto/poktroll/service/params.proto
  proto/poktroll/service/query.proto
  proto/poktroll/service/tx.proto
  proto/poktroll/shared/service.proto
  testutil/keeper/service.go
  testutil/network/network.go
  testutil/service/mocks/mocks.go
  x/service/keeper/keeper.go
  x/service/keeper/msg_server.go
  x/service/keeper/msg_server_add_service.go
  x/service/keeper/msg_server_add_service_test.go
  x/service/keeper/msg_server_test.go
  x/service/keeper/msg_update_params.go
  x/service/keeper/msg_update_params_test.go
  x/service/keeper/params.go
  x/service/keeper/params_test.go
  x/service/keeper/query.go
  x/service/keeper/query_params.go
  x/service/keeper/query_params_test.go
  x/service/keeper/query_service.go
  x/service/keeper/query_service_test.go
  x/service/keeper/service.go
  x/service/keeper/service_test.go
  x/service/module/autocli.go
  x/service/module/genesis.go
  x/service/module/genesis_test.go
  x/service/module/module.go
  x/service/module/simulation.go
  x/service/module/tx.go
  x/service/module/tx_add_service.go
  x/service/module/tx_add_service_test.go
  x/service/simulation/add_service.go
  x/service/simulation/helpers.go
  x/service/types/codec.go
  x/service/types/errors.go
  x/service/types/expected_keepers.go
  x/service/types/genesis.go
  x/service/types/genesis_test.go
  x/service/types/key_service.go
  x/service/types/keys.go
  x/service/types/message_add_service.go
  x/service/types/message_add_service_test.go
  x/service/types/message_update_params.go
  x/service/types/params.go
  x/service/types/types.go
  x/shared/types/types.go
Labels: service, code health
