Repository pokt-network/poktroll, pull requests merged in 2024-04, with the labels that each got.

#453 [Review] out-of-band review of #444
  pkg/client/block/client.go
  pkg/client/block/client_integration_test.go
  pkg/client/block/client_test.go
  pkg/client/interface.go
  pkg/client/tx/client.go
  pkg/deps/config/suppliers.go
  pkg/relayer/proxy/relay_verifier.go
  pkg/relayer/session/claim.go
  pkg/relayer/session/proof.go
  pkg/sdk/deps_builder.go
  pkg/sdk/session.go
  testutil/testclient/testblock/client.go
Labels: code health

#455 [LocalNet] Fix hot reloading
  .github/workflows-helpers/run-e2e-test-job-template.yaml
  Dockerfile.dev
  Tiltfile
  localnet/kubernetes/values-common.yaml
Labels: bug

#434 [LocalNet] Add scalable gateways
  Tiltfile
  localnet/kubernetes/values-gateway.yaml
Labels: infra

#450 [RelayMiner] Handle gzip compression
  pkg/relayer/proxy/relay_builders.go
  pkg/relayer/proxy/synchronous.go
Labels: relayminer, push-image, devnet, devnet-test-e2e

#467 [Docs] Fix docs and adjust CI to catch bad links
  .github/workflows/upload-pages-artifact.yml
  docusaurus/docs/developer_guide/quickstart.md
Labels: documentation

#465 [Docs] add time & eliminate hard-to-measure metrics
  docusaurus/docs/internal_infrastructure/testing/load_testing_plan_1.md
Labels: documentation, loadtest

#475 [LocalNet] Add observability stack
  Tiltfile
  config.yml
  docusaurus/docs/internal_infrastructure/access_dashboard_on_service.png
  docusaurus/docs/internal_infrastructure/grafana_save_dashboard.png
  docusaurus/docs/internal_infrastructure/localnet.md
  localnet/grafana-dashboards/appgateserver.json
  localnet/grafana-dashboards/cometbft.json
  localnet/grafana-dashboards/go-runtime.json
  localnet/grafana-dashboards/relayminer.json
  localnet/kubernetes/observability-loki-stack.yaml
  localnet/kubernetes/observability-prometheus-stack.yaml
  localnet/poktrolld/config/app.toml
  localnet/poktrolld/config/config.toml
Labels: documentation, infra, tooling

#480 [LocalNet] Switch validator logs to json
  Tiltfile
Labels: infra, tooling

#466 [Tooling] Makefile checkers when starting localnet
  Makefile
  pkg/client/tx/client_test.go
Labels: push-image, tooling, devnet, devnet-test-e2e

#473 Update test instructions pull_request_template.md
  .github/pull_request_template.md
Labels: testing

#468 [Metrics] Additional off-chain metrics
  pkg/appgateserver/error_reply.go
  pkg/appgateserver/metrics.go
  pkg/appgateserver/synchronous.go
  pkg/relayer/proxy/error_reply.go
  pkg/relayer/proxy/metrics.go
  pkg/relayer/proxy/synchronous.go
Labels: off-chain, push-image, devnet, devnet-test-e2e

#470 [Testing] chore: add make targets & update feature path logging
  Makefile
  e2e/tests/0_settlement.feature
  e2e/tests/init_test.go
Labels: testing, tooling

#471 [Docs] update supplier actor CLI section
  docusaurus/docs/protocol/actors/supplier.md
  docusaurus/yarn.lock
Labels: documentation

#472 [SMT] Updated smt release from v0.9.2 -> v0.10.2
  go.mod
  go.sum
  pkg/client/tx/client_test.go
  pkg/relayer/session/session_test.go
  x/proof/keeper/msg_server_submit_proof.go
  x/proof/keeper/msg_server_submit_proof_test.go
Labels: push-image, devnet, devnet-test-e2e, smt, Audit

#482 [Tooling] Add application stake/unstake/delegate logs
  localnet/grafana-dashboards/application_logs.json
  localnet/grafana-dashboards/cometbft.json
Labels: tooling, observability

#449 [Metrics] feat: Initial on-chain metrics implementation
  app/app.go
  go.mod
  telemetry/block.go
  telemetry/event_counters.go
  x/application/keeper/msg_server_delegate_to_gateway.go
  x/application/keeper/msg_server_stake_application.go
  x/application/keeper/msg_server_undelegate_from_gateway.go
  x/application/keeper/msg_server_unstake_application.go
  x/gateway/keeper/msg_server_stake_gateway.go
  x/gateway/keeper/msg_server_unstake_gateway.go
  x/proof/keeper/msg_server_create_claim.go
  x/proof/keeper/msg_server_submit_proof.go
  x/service/keeper/msg_server_add_service.go
  x/supplier/keeper/msg_server_stake_supplier.go
  x/supplier/keeper/msg_server_unstake_supplier.go
  x/tokenomics/keeper/settle_pending_claims.go
  x/tokenomics/keeper/settle_session_accounting.go
Labels: infra, on-chain, push-image, devnet, devnet-test-e2e, loadtest

#423 chore: add todos for future iterations/improvements
  pkg/client/interface.go
  pkg/relayer/protocol/difficulty.go
  pkg/relayer/protocol/difficulty_test.go
  pkg/relayer/session/sessiontree.go
  x/proof/keeper/msg_server_submit_proof.go
  x/proof/keeper/msg_server_submit_proof_test.go
  x/proof/keeper/proof.go
Labels: code health, push-image, devnet, devnet-test-e2e

#441 [SDK] Client TLS Support
  pkg/client/events/websocket/dialer.go
  pkg/deps/config/suppliers.go
  pkg/sdk/deps_builder.go
  pkg/sdk/deps_builder_test.go
  pkg/sdk/urls.go
  pkg/sdk/urls_test.go
Labels: enhancement, off-chain, push-image, devnet, devnet-test-e2e, sdk

#485 [LocalNet] Add option to turn on/off delve
  Tiltfile
Labels: infra, tooling

#481 [Testing] Add application staking with Makefile targets for app and gateways
  Makefile
  e2e/tests/init_test.go
  e2e/tests/stake_app.feature
  e2e/tests/stake_gateway.feature
Labels: testing, push-image, tooling, devnet, devnet-test-e2e

#477 [Config] feat: Simplify relay miner config
  docusaurus/docs/operate/configs/app_staking_config.md
  docusaurus/docs/operate/configs/relayminer_config.md
  docusaurus/docs/operate/configs/supplier_staking_config.md
  docusaurus/yarn.lock
  localnet/kubernetes/values-relayminer-1.yaml
  localnet/kubernetes/values-relayminer-2.yaml
  localnet/kubernetes/values-relayminer-3.yaml
  localnet/kubernetes/values-relayminer-common.yaml
  localnet/poktrolld/config/relayminer_config.yaml
  localnet/poktrolld/config/relayminer_config_full_example.yaml
  localnet/poktrolld/config/supplier1_stake_config.yaml
  localnet/poktrolld/config/supplier2_stake_config.yaml
  localnet/poktrolld/config/supplier3_stake_config.yaml
  pkg/relayer/cmd/cmd.go
  pkg/relayer/config/errors.go
  pkg/relayer/config/proxies_config_hydrator.go
  pkg/relayer/config/proxy_http_config_parser.go
  pkg/relayer/config/relayminer_configs_reader.go
  pkg/relayer/config/relayminer_configs_reader_test.go
  pkg/relayer/config/servers_config_hydrator.go
  pkg/relayer/config/supplier_hydrator.go
  pkg/relayer/config/suppliers_config_hydrator.go
  pkg/relayer/config/types.go
  pkg/relayer/proxy/error_reply.go
  pkg/relayer/proxy/errors.go
  pkg/relayer/proxy/metrics.go
  pkg/relayer/proxy/options.go
  pkg/relayer/proxy/proxy.go
  pkg/relayer/proxy/proxy_test.go
  pkg/relayer/proxy/server_builder.go
  pkg/relayer/proxy/synchronous.go
  pkg/relayer/session/proof.go
  testutil/testproxy/relayerproxy.go
  x/proof/keeper/msg_server_submit_proof.go
  x/supplier/config/supplier_configs_reader.go
  x/supplier/config/supplier_configs_reader_test.go
  x/supplier/module/tx_stake_supplier_test.go
Labels: relayminer, off-chain, push-image, devnet, devnet-test-e2e

#479 [Tooling] Add claim/proof/settlement dashboard & link
  Makefile
  localnet/grafana-dashboards/claim_proof_logs.json
  localnet/grafana-dashboards/cometbft.json
Labels: tooling

#444 [BlockClient] Refactor BlockClient to fetch latest block at init
  pkg/appgateserver/cmd/cmd.go
  pkg/client/block/block_result.go
  pkg/client/block/client.go
  pkg/client/block/client_integration_test.go
  pkg/client/block/client_test.go
  pkg/client/events/replay_client.go
  pkg/client/interface.go
  pkg/client/tx/client.go
  pkg/deps/config/suppliers.go
  pkg/observable/channel/replay.go
  pkg/observable/channel/replay_test.go
  pkg/observable/interface.go
  pkg/relayer/cmd/cmd.go
  pkg/relayer/proxy/relay_verifier.go
  pkg/relayer/session/claim.go
  pkg/relayer/session/proof.go
  pkg/sdk/deps_builder.go
  pkg/sdk/session.go
  testutil/testclient/testblock/client.go
  testutil/testclient/testeventsquery/client.go
  testutil/testproxy/relayerproxy.go
Labels: session, off-chain, push-image, devnet, devnet-test-e2e

#500 [LocalNet][Hotfix] Turn off pproff by default
  localnet/kubernetes/values-appgateserver.yaml
  localnet/kubernetes/values-gateway.yaml
  localnet/kubernetes/values-relayminer-common.yaml
Labels: bug

#504 [LocalNet] Remove tilt-restart-wrapper
  Tiltfile
Labels: bug, infra, tooling

#505 [Bug] Fix pprof endpoint
  localnet/kubernetes/values-appgateserver.yaml
  localnet/kubernetes/values-gateway.yaml
  localnet/kubernetes/values-relayminer-common.yaml
  pkg/appgateserver/cmd/cmd.go
  pkg/appgateserver/server.go
  pkg/relayer/cmd/cmd.go
  pkg/relayer/relayminer.go
Labels: bug

#507 [RelayMiner] Support https backend urls
  pkg/relayer/config/proxy_http_config_parser.go
  pkg/relayer/config/supplier_hydrator.go
  pkg/relayer/proxy/synchronous.go
Labels: relayminer, off-chain

#498 [Testing] Supplier staking E2E test
  Makefile
  e2e/tests/init_test.go
  e2e/tests/stake_supplier.feature
Labels: supplier, testing, push-image, devnet, devnet-test-e2e, utility

#509 [Utility] Update SessionSettlement when app goes into a negative amount
  x/tokenomics/keeper/settle_pending_claims.go
  x/tokenomics/keeper/settle_session_accounting.go
  x/tokenomics/keeper/settle_session_accounting_test.go
  x/tokenomics/types/errors.go
Labels: protocol, on-chain, push-image, devnet, devnet-test-e2e, utility

#502 [Dashboard] Supplier logs dashboard
  localnet/grafana-dashboards/cometbft.json
  localnet/grafana-dashboards/supplier_logs.json
Labels: tooling

#503 [Tooling] Add gateway stake/unstake/ logs
  Makefile
  localnet/grafana-dashboards/cometbft.json
  localnet/grafana-dashboards/gateway_logs.json
Labels: on-chain, tooling

#506 [CI] Add GATEWAY_URL envar for e2e tests
  .github/workflows-helpers/run-e2e-test-job-template.yaml
  Makefile
Labels: infra
