Repository pokt-network/poktroll, pull requests merged in 2025-02, with the labels that each got.

#1043 [Upgrades] v0.0.12 upgrade
  app/upgrades.go
  app/upgrades/historical.go
  app/upgrades/types.go
  app/upgrades/v0.0.12.go
  docusaurus/docs/protocol/upgrades/upgrade_list.md
  localnet/poktrolld/config/relayminer_config_localnet_vscode.yaml
Labels: protocol

#1056 [CI][Quick change] downgrade docker/login-action version
  .github/workflows/release-artifacts.yml
Labels: infra

#1032 [Migration] scaffold: module migration
  api/poktroll/migration/genesis.pulsar.go
  api/poktroll/migration/module/module.pulsar.go
  api/poktroll/migration/params.pulsar.go
  api/poktroll/migration/query.pulsar.go
  api/poktroll/migration/query_grpc.pb.go
  api/poktroll/migration/tx.pulsar.go
  api/poktroll/migration/tx_grpc.pb.go
  app/app.go
  app/app_config.go
  app/keepers/types.go
  proto/poktroll/migration/genesis.proto
  proto/poktroll/migration/module/module.proto
  proto/poktroll/migration/params.proto
  proto/poktroll/migration/query.proto
  proto/poktroll/migration/tx.proto
  testutil/keeper/migration.go
  x/migration/keeper/keeper.go
  x/migration/keeper/msg_server.go
  x/migration/keeper/msg_server_test.go
  x/migration/keeper/msg_update_params.go
  x/migration/keeper/msg_update_params_test.go
  x/migration/keeper/params.go
  x/migration/keeper/params_test.go
  x/migration/keeper/query.go
  x/migration/keeper/query_params.go
  x/migration/keeper/query_params_test.go
  x/migration/module/autocli.go
  x/migration/module/genesis.go
  x/migration/module/genesis_test.go
  x/migration/module/module.go
  x/migration/module/simulation.go
  x/migration/simulation/helpers.go
  x/migration/types/codec.go
  x/migration/types/errors.go
  x/migration/types/expected_keepers.go
  x/migration/types/genesis.go
  x/migration/types/genesis.pb.go
  x/migration/types/genesis_test.go
  x/migration/types/keys.go
  x/migration/types/msg_update_params.go
  x/migration/types/params.go
  x/migration/types/params.pb.go
  x/migration/types/query.pb.go
  x/migration/types/query.pb.gw.go
  x/migration/types/tx.pb.go
  x/migration/types/types.go
Labels: on-chain, push-image, devnet, devnet-test-e2e, p0, consensus-breaking, migration

#1055 [OpenAPI] Add `Dockerfile` to reliability generate the OpenAPI spec using `ignite`
  Makefile
  docs/static/openapi.json
  docs/static/openapi.yml
  proto/Dockerfile.ignite
Labels: enhancement

#1064 [Docs] Update release process to include homebrew tap formula
  docusaurus/docs/operate/upgrades/release_process.md
  docusaurus/docs/tools/user_guide/poktrolld_cli.md
Labels: documentation

#1039 [Morse->Shannon Migration] state export/import - collect accounts
  api/poktroll/application/types.pulsar.go
  api/poktroll/migration/morse_offchain.pulsar.go
  api/poktroll/migration/morse_onchain.pulsar.go
  cmd/poktrolld/cmd/commands.go
  cmd/poktrolld/cmd/migrate/errors.go
  cmd/poktrolld/cmd/migrate/migrate.go
  cmd/poktrolld/cmd/migrate/migrate_test.go
  cmd/poktrolld/cmd/migrate/types.go
  docusaurus/docs/operate/morse_migration/_category_.json
  docusaurus/docs/operate/morse_migration/morse-migration.md
  docusaurus/docs/operate/networks/_category_.json
  docusaurus/docs/operate/upgrades/contigency_plans.md
  docusaurus/docs/operate/upgrades/recovery_from_chain_halt.md
  proto/poktroll/application/types.proto
  proto/poktroll/migration/morse_offchain.proto
  proto/poktroll/migration/morse_onchain.proto
  x/application/types/types.pb.go
  x/migration/types/morse_account_state.go
  x/migration/types/morse_offchain.pb.go
  x/migration/types/morse_onchain.pb.go
Labels: on-chain, push-image, devnet, devnet-test-e2e, consensus-breaking, migration

#1012 [Docs] Validator cheatsheet and walkthrough
  docusaurus/docs/operate/cheat_sheets/gateway_cheatsheet.md
  docusaurus/docs/operate/cheat_sheets/supplier_cheatsheet.md
  docusaurus/docs/operate/cheat_sheets/validator_cheatsheet.md
  docusaurus/docs/operate/faq/validator_faq.md
  docusaurus/docs/operate/upgrades/release_process.md
  docusaurus/docs/operate/walkthroughs/full_node_docker.md
  docusaurus/docs/operate/walkthroughs/validator_walkthrough.md
  docusaurus/docs/protocol/governance/params.md
  docusaurus/docusaurus.config.js
  tools/installer/full-node.sh
Labels: documentation

#1061 chore: add open api spec into the docs
  docusaurus/docs/tools/tools/open_api.md
  docusaurus/package-lock.json
  docusaurus/package.json
  docusaurus/src/components/OpenAPI.js
  docusaurus/static/openapi.json
  docusaurus/yarn.lock
Labels: documentation

#1081 [DOCS] Fix Docusaurus deploy from Open API embed
  Makefile
  docusaurus/docs/tools/tools/open_api.md
  docusaurus/package-lock.json
  docusaurus/package.json
  docusaurus/src/components/OpenAPI.js
  docusaurus/src/css/custom.css
  docusaurus/static/openapi.json
  docusaurus/yarn.lock
  makefiles/checks.mk
Labels: bug, documentation

#1074 [Dependencies] bump cosmos-sdk & cosmovisor
  Makefile
  go.mod
  go.sum
Labels: push-image, devnet, devnet-test-e2e, dependencies

#1067 [Tokenomics] Refactor token distribution to use `big.Rat` instead of `float64`
  pkg/encoding/decimal.go
  tests/integration/application/min_stake_test.go
  x/tokenomics/keeper/token_logic_modules.go
  x/tokenomics/keeper/token_logic_modules_test.go
  x/tokenomics/token_logic_module/distribution.go
  x/tokenomics/token_logic_module/global_mint.go
  x/tokenomics/token_logic_module/reimbursement_requests.go
  x/tokenomics/token_logic_module/relay_burn_equals_mint.go
Labels: code health, push-image, devnet, devnet-test-e2e, tokenomics

#1084 [Docs] Followup on making homebrew troubleshooting easier to identify
  cmd/poktrolld/cmd/root.go
  docusaurus/docs/tools/user_guide/poktrolld_cli.md
Labels: documentation

#1087 Update links to Soothe's Explorer and GraphQL Playground
  docusaurus/docs/tools/tools/shannon_alpha.md
  docusaurus/docs/tools/tools/shannon_beta.md
Labels: documentation

#1077 [RelayMiner] Introduce new relay authenticator for relay signing and verification
  pkg/relayer/cmd/cmd.go
  pkg/relayer/interface.go
  pkg/relayer/proxy/errors.go
  pkg/relayer/proxy/options.go
  pkg/relayer/proxy/proxy.go
  pkg/relayer/proxy/proxy_test.go
  pkg/relayer/proxy/relay_builders.go
  pkg/relayer/proxy/relay_meter.go
  pkg/relayer/proxy/relay_signer.go
  pkg/relayer/proxy/server_builder.go
  pkg/relayer/proxy/synchronous.go
  pkg/relayer/relay_authenticator/errors.go
  pkg/relayer/relay_authenticator/options.go
  pkg/relayer/relay_authenticator/relay_authenticator.go
  pkg/relayer/relay_authenticator/relay_authenticator_test.go
  pkg/relayer/relay_authenticator/relay_signer.go
  pkg/relayer/relay_authenticator/relay_verifier.go
  testutil/sample/sample.go
  testutil/testproxy/relayerproxy.go
Labels: relayminer, proxy, off-chain, push-image, devnet, devnet-test-e2e

#1083 [Docs] Prevent `poktroll` user from prompting a `poktrolld` password with `os` backend
  docusaurus/docs/tools/user_guide/send-tokens.md
  docusaurus/docs/tools/user_guide/user_keyring.md
Labels: documentation

#1088 [Docs] simplify poktrolld install doc
  docusaurus/docs/tools/user_guide/poktrolld_cli.md
Labels: documentation

#1073 [RelayMiner] Add websockets support
  Tiltfile
  config.yml
  docusaurus/docs/protocol/primitives/async_service_mining.md
  e2e/tests/stake_app.feature
  go.mod
  localnet/kubernetes/values-relayminer-1.yaml
  localnet/kubernetes/values-relayminer-2.yaml
  localnet/kubernetes/values-relayminer-3.yaml
  localnet/poktrolld/config/app.toml
  localnet/poktrolld/config/application3_stake_config.yaml
  localnet/poktrolld/config/config.toml
  localnet/poktrolld/config/relayminer_config.yaml
  localnet/poktrolld/config/relayminer_config_full_example.yaml
  localnet/poktrolld/config/relayminer_config_localnet_vscode.yaml
  localnet/poktrolld/config/supplier1_stake_config.yaml
  localnet/poktrolld/config/supplier2_stake_config.yaml
  localnet/poktrolld/config/supplier3_stake_config.yaml
  makefiles/relay.mk
  pkg/relayer/config/supplier_hydrator.go
  pkg/relayer/config/types.go
  pkg/relayer/http_request.go
  pkg/relayer/metrics.go
  pkg/relayer/proxy/async.go
  pkg/relayer/proxy/error_reply.go
  pkg/relayer/proxy/http_server.go
  pkg/relayer/proxy/proxy.go
  pkg/relayer/proxy/relay_builders.go
  pkg/relayer/proxy/server_builder.go
  pkg/relayer/proxy/sync.go
  pkg/relayer/proxy/synchronous.go
  pkg/relayer/proxy/websockets/bridge.go
  pkg/relayer/proxy/websockets/connection.go
  pkg/relayer/proxy/websockets/errors.go
  x/gateway/keeper/msg_server_unstake_gateway.go
  x/shared/types/service.go
Labels: relayminer, proxy, off-chain, push-image, devnet, devnet-test-e2e

#1090 [Bug] fix: E2E test `s/X-App-Address/App-Address/`
  e2e/tests/node.go
  load-testing/tests/relays_stress_helpers_test.go
  makefiles/relay.mk
Labels: gateway, off-chain, push-image, devnet, devnet-test-e2e

#1072 [Morse->Shannon Migration] scaffold & impl.: `MsgImportMorseClaimableAccounts` message
  api/poktroll/migration/event.pulsar.go
  api/poktroll/migration/morse_onchain.pulsar.go
  api/poktroll/migration/tx.pulsar.go
  api/poktroll/migration/tx_grpc.pb.go
  cmd/poktrolld/cmd/migrate/migrate_test.go
  cmd/poktrolld/cmd/migrate/types.go
  e2e/tests/init_test.go
  e2e/tests/migration_error.feature
  e2e/tests/migration_steps_test.go
  e2e/tests/migration_success.feature
  go.mod
  makefiles/tests.mk
  proto/poktroll/migration/event.proto
  proto/poktroll/migration/morse_onchain.proto
  proto/poktroll/migration/tx.proto
  testutil/testmigration/fixtures.go
  x/migration/keeper/morse_claimable_account.go
  x/migration/keeper/morse_claimable_account_test.go
  x/migration/keeper/msg_server_import_morse_claimable_accounts.go
  x/migration/keeper/msg_server_import_morse_claimable_accounts_test.go
  x/migration/keeper/query_morse_claimable_account_test.go
  x/migration/module/autocli.go
  x/migration/module/genesis.go
  x/migration/module/genesis_test.go
  x/migration/module/simulation.go
  x/migration/simulation/import_morse_claimable_accounts.go
  x/migration/types/codec.go
  x/migration/types/errors.go
  x/migration/types/event.pb.go
  x/migration/types/genesis.go
  x/migration/types/genesis_test.go
  x/migration/types/message_import_morse_claimable_accounts.go
  x/migration/types/message_import_morse_claimable_accounts_test.go
  x/migration/types/morse_onchain.pb.go
  x/migration/types/tx.pb.go
Labels: on-chain, push-image, devnet, devnet-test-e2e, consensus-breaking, migration

#1075 [Morse->Shannon Migration] scaffold: `MsgClaimMorseAccount` message
  api/poktroll/migration/tx.pulsar.go
  api/poktroll/migration/tx_grpc.pb.go
  proto/poktroll/migration/tx.proto
  x/migration/keeper/msg_server_claim_morse_account.go
  x/migration/module/autocli.go
  x/migration/module/simulation.go
  x/migration/simulation/claim_morse_account.go
  x/migration/types/codec.go
  x/migration/types/message_claim_morse_account.go
  x/migration/types/message_claim_morse_account_test.go
  x/migration/types/tx.pb.go
Labels: on-chain, push-image, devnet, devnet-test-e2e, consensus-breaking, migration

#1097 [Upgrade] TestNet v0.0.13 upgrade
  app/upgrades.go
  app/upgrades/v0.0.13.go
  docusaurus/docs/operate/upgrades/upgrade_procedure.md
Labels: code health, push-image
